export enum UserRole {
  HOD = "HOD",
  KPI_COORDINATOR = "KPI_COORDINATOR",
  FACULTY = "FACULTY",
  QAC = "QAC",
}

export enum KpiStatus {
  PENDING = "PENDING",
  OVERDUE = "OVERDUE",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  REVISION = "REVISION",
}
